# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NIBM App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NIBM App
  
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Nuke', '~> 7.0'
  pod 'BiometricAuthentication'
  pod 'Alamofire', '~> 5.0.0-rc.2'
  pod 'SwiftyJSON'

  target 'NIBM AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NIBM AppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
